services:
  x-base: &base
    image: synthalingua:latest
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    volumes:
      - models_cache:/app/Synthalingua/models
      - /usr/share/sounds/alsa:/usr/share/sounds/alsa
      - ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native

  jp-streams:
    <<: *base
    image: synthalingua:latest
    container_name: synthalingua-jp
    command: python transcribe_audio.py --ram ${SYN_RAM_USAGE} --device=${SYN_DEVICE}
      --stream_translate --stream_language Japanese --record_timeout ${SYN_RECORD_TIMEOUT}
      --stream_chunks=${SYN_STREAM_CHUNKS} --stream_original_text --stream ${URL}

  jp-pc-audio:
    <<: *base
    image: synthalingua:latest
    container_name: synthalingua-jp-audio
    command: python transcribe_audio.py --ram ${SYN_RAM_USAGE} 
      --microphone_enabled=true --mic_calibration_time=${SYN_MIC_CALIBRATION_TIME}
      --translate --language Japanese --target_language English 
      --energy_threshold=${SYN_ENERGY_THRESHOLD} --phrase_timeout=${SYN_PHRASE_TIMEOUT}
  
volumes:
  models_cache:

    
    